url: http://zted.github.io
baseurl: ""

# Site Settings
# Also displayed at the top
title:  Top
description: "Ted Z"
keywords: "jekyll, theme"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "img/earth.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]
