# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: HALLO!
email: not.here@unfound.com
description: > # this means to ignore newlines until "baseurl:"
    Hi there! I am making my first website (and a total noob at that)
    with the help of jekyll so please check back in a few weeks!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  zted

# Build settings
markdown: kramdown
